// Copyright 2024-2026 Firefly Software Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

namespace FireflyFramework.Cli.Templates;

public static class ServiceScaffold
{
    public static void Render(string root, TemplateContext ctx)
    {
        var modules = new[] { "Interfaces", "Models", "Core", "Web", "Sdk" };
        foreach (var m in modules)
        {
            var dir = Path.Combine(root, $"{ctx.Namespace}.{m}");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, $"{ctx.Namespace}.{m}.csproj"), CsProj(ctx, m));
            File.WriteAllText(Path.Combine(dir, "Placeholder.cs"),
                $"namespace {ctx.Namespace}.{m};\n\npublic static class Placeholder {{ public const string ModuleName = \"{m}\"; }}\n");
        }

        var slnPath = Path.Combine(root, $"{ctx.Namespace}.sln");
        File.WriteAllText(slnPath, $"# {ctx.Namespace} solution scaffold ({ctx.Tier} tier)\n");
        File.WriteAllText(Path.Combine(root, "README.md"),
            $"# {ctx.ServiceName}\n\nFirefly **{ctx.Tier}** tier microservice scaffolded by `firefly new`.\n");
    }

    private static string CsProj(TemplateContext ctx, string module) => $@"<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <RootNamespace>{ctx.Namespace}.{module}</RootNamespace>
    <PackageId>{ctx.Namespace}.{module}</PackageId>
  </PropertyGroup>
</Project>
";
}

public static class HandlerScaffold
{
    public static string Render(string name, string kind)
    {
        var iface = kind == "command" ? "ICommandHandler" : "IQueryHandler";
        var marker = kind == "command" ? "ICommand" : "IQuery";
        return $@"// Generated by `firefly handler {kind} {name}`
using FireflyFramework.Cqrs;

public sealed record {name}({marker.TrimStart('I')}) : {marker};

public sealed class {name}Handler : {iface}<{name}>
{{
    public Task HandleAsync({name} input, CancellationToken ct) => Task.CompletedTask;
}}
";
    }
}

public static class SagaScaffold
{
    public static string Render(string name, int steps)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"// Generated by `firefly saga {name}`");
        sb.AppendLine("using FireflyFramework.Orchestration.Saga;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {name}Saga");
        sb.AppendLine("{");
        for (int i = 1; i <= steps; i++)
        {
            sb.AppendLine($"    public Task Step{i}Async(CancellationToken ct) => Task.CompletedTask;");
            sb.AppendLine($"    public Task CompensateStep{i}Async(CancellationToken ct) => Task.CompletedTask;");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }
}
