// Copyright 2024-2026 Firefly Software Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

namespace FireflyFramework.Cli.Templates;

/// <summary>Renders the canonical 5-module Firefly microservice scaffold.</summary>
public static class ServiceScaffold
{
    private static readonly string[] Modules = { "Interfaces", "Models", "Core", "Web", "Sdk" };

    public static void Render(string root, TemplateContext ctx)
    {
        foreach (var m in Modules)
        {
            var dir = Path.Combine(root, $"{ctx.Namespace}.{m}");
            Directory.CreateDirectory(dir);
            File.WriteAllText(Path.Combine(dir, $"{ctx.Namespace}.{m}.csproj"), CsProj(ctx, m));
            File.WriteAllText(Path.Combine(dir, $"{m}Marker.cs"),
                $"namespace {ctx.Namespace}.{m};\n\npublic static class {m}Marker {{ public const string ModuleName = \"{m}\"; }}\n");
        }

        // Real .NET solution file (Visual Studio Format 12.00) so users can immediately `dotnet build`.
        File.WriteAllText(Path.Combine(root, $"{ctx.Namespace}.sln"), Sln(ctx));
        File.WriteAllText(Path.Combine(root, "README.md"),
            $"# {ctx.ServiceName}\n\nFirefly **{ctx.Tier}** tier microservice scaffolded by `firefly new`.\n\n" +
            "## Modules\n\n" +
            string.Join("\n", Modules.Select(m => $"- `{ctx.Namespace}.{m}`")) + "\n\n" +
            "## Build\n\n```bash\ndotnet build\n```\n");
    }

    private static string CsProj(TemplateContext ctx, string module) => $"""
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <TargetFramework>net10.0</TargetFramework>
            <Nullable>enable</Nullable>
            <ImplicitUsings>enable</ImplicitUsings>
            <RootNamespace>{ctx.Namespace}.{module}</RootNamespace>
            <PackageId>{ctx.Namespace}.{module}</PackageId>
          </PropertyGroup>
        </Project>
        """;

    private static string Sln(TemplateContext ctx)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("Microsoft Visual Studio Solution File, Format Version 12.00");
        sb.AppendLine("# Visual Studio Version 17");
        foreach (var m in Modules)
        {
            var guid = Guid.NewGuid().ToString("B").ToUpperInvariant();
            sb.AppendLine($"Project(\"{{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}}\") = \"{ctx.Namespace}.{m}\", \"{ctx.Namespace}.{m}/{ctx.Namespace}.{m}.csproj\", \"{guid}\"");
            sb.AppendLine("EndProject");
        }
        sb.AppendLine("Global");
        sb.AppendLine("\tGlobalSection(SolutionConfigurationPlatforms) = preSolution");
        sb.AppendLine("\t\tDebug|Any CPU = Debug|Any CPU");
        sb.AppendLine("\t\tRelease|Any CPU = Release|Any CPU");
        sb.AppendLine("\tEndGlobalSection");
        sb.AppendLine("EndGlobal");
        return sb.ToString();
    }
}

/// <summary>
/// Generates a CQRS handler skeleton matching the live <c>ICommandHandler&lt;TCommand,TResult&gt;</c> /
/// <c>IQueryHandler&lt;TQuery,TResult&gt;</c> contracts in <c>FireflyFramework.Cqrs</c>.
/// </summary>
public static class HandlerScaffold
{
    public static string Render(string name, string kind)
    {
        if (kind == "command")
        {
            return $$"""
                // Generated by `firefly handler command {{name}}`
                // Implements ICommandHandler from FireflyFramework.Cqrs.
                //
                // Replace `Unit` with a real result type if the command should return a value.

                using FireflyFramework.Cqrs;

                namespace YourService.Core;

                public readonly record struct Unit { public static Unit Value => default; }

                public sealed record {{name}}(/* TODO: input fields */) : ICommand<Unit>;

                public sealed class {{name}}Handler : ICommandHandler<{{name}}, Unit>
                {
                    public Task<Unit> HandleAsync({{name}} input, CancellationToken ct)
                    {
                        // TODO: implement
                        return Task.FromResult(Unit.Value);
                    }
                }
                """;
        }

        return $$"""
            // Generated by `firefly handler query {{name}}`
            // Implements IQueryHandler from FireflyFramework.Cqrs.

            using FireflyFramework.Cqrs;

            namespace YourService.Core;

            public sealed record {{name}}Result(/* TODO: result fields */);

            public sealed record {{name}}(/* TODO: input fields */) : IQuery<{{name}}Result>;

            public sealed class {{name}}Handler : IQueryHandler<{{name}}, {{name}}Result>
            {
                public Task<{{name}}Result> HandleAsync({{name}} input, CancellationToken ct)
                {
                    // TODO: implement
                    return Task.FromResult(new {{name}}Result(/* fields */));
                }
            }
            """;
    }
}

/// <summary>
/// Generates a saga skeleton compatible with <c>FireflyFramework.Orchestration</c>:
/// each Step* method is the forward action; Compensate* is its reversal. Wire the
/// methods into a saga topology in your composition root.
/// </summary>
public static class SagaScaffold
{
    public static string Render(string name, int steps)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"// Generated by `firefly saga {name}`");
        sb.AppendLine("// Forward + compensate methods for each saga step. Wire into a saga topology");
        sb.AppendLine("// using FireflyFramework.Orchestration in your composition root.");
        sb.AppendLine();
        sb.AppendLine("namespace YourService.Core;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {name}Saga");
        sb.AppendLine("{");
        for (int i = 1; i <= steps; i++)
        {
            sb.AppendLine($"    public Task Step{i}Async(CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine("        // TODO: forward action");
            sb.AppendLine("        return Task.CompletedTask;");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine($"    public Task CompensateStep{i}Async(CancellationToken ct)");
            sb.AppendLine("    {");
            sb.AppendLine($"        // TODO: reverse Step{i}");
            sb.AppendLine("        return Task.CompletedTask;");
            sb.AppendLine("    }");
            if (i < steps) sb.AppendLine();
        }
        sb.AppendLine("}");
        return sb.ToString();
    }
}
