using System.Text;
using Avro;
using Avro.IO;
using Avro.Specific;
using FireflyFramework.Eda.Events;

namespace FireflyFramework.Eda.Serialization;

/// <summary>
/// Avro binary serializer. Mirrors Java <c>AvroMessageSerializer</c>. Works with
/// classes generated by avrogen.exe / avrogen-csharp that implement <see cref="ISpecificRecord"/>.
/// </summary>
public sealed class AvroMessageSerializer : IMessageSerializer
{
    public SerializationFormat Format => SerializationFormat.Avro;

    public byte[] Serialize<T>(T value)
    {
        if (value is not ISpecificRecord record)
        {
            throw new InvalidOperationException(
                $"Avro serialization requires Avro-generated types implementing ISpecificRecord; got {typeof(T).Name}.");
        }

        using var stream = new MemoryStream();
        var encoder = new BinaryEncoder(stream);
        var writer = new SpecificDefaultWriter(record.Schema);
        writer.Write(record.Schema, value, encoder);
        return stream.ToArray();
    }

    public T? Deserialize<T>(byte[] data)
    {
        var schemaInstance = Activator.CreateInstance<T>() as ISpecificRecord
            ?? throw new InvalidOperationException(
                $"Avro deserialization requires types implementing ISpecificRecord; got {typeof(T).Name}.");

        using var stream = new MemoryStream(data);
        var decoder = new BinaryDecoder(stream);
        var reader = new SpecificDefaultReader(schemaInstance.Schema, schemaInstance.Schema);
        return (T?)reader.Read(schemaInstance, decoder);
    }
}
