// Copyright 2024-2026 Firefly Software Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System.Text;
using Avro;
using Avro.IO;
using Avro.Specific;
using FireflyFramework.Eda.Events;

namespace FireflyFramework.Eda.Serialization;

/// <summary>
/// Avro binary serializer. Mirrors Java <c>AvroMessageSerializer</c>. Works with
/// classes generated by avrogen.exe / avrogen-csharp that implement <see cref="ISpecificRecord"/>.
/// </summary>
public sealed class AvroMessageSerializer : IMessageSerializer
{
    public SerializationFormat Format => SerializationFormat.Avro;

    public byte[] Serialize<T>(T value)
    {
        if (value is not ISpecificRecord record)
        {
            throw new InvalidOperationException(
                $"Avro serialization requires Avro-generated types implementing ISpecificRecord; got {typeof(T).Name}.");
        }

        using var stream = new MemoryStream();
        var encoder = new BinaryEncoder(stream);
        var writer = new SpecificDefaultWriter(record.Schema);
        writer.Write(record.Schema, value, encoder);
        return stream.ToArray();
    }

    public T? Deserialize<T>(byte[] data)
    {
        var schemaInstance = Activator.CreateInstance<T>() as ISpecificRecord
            ?? throw new InvalidOperationException(
                $"Avro deserialization requires types implementing ISpecificRecord; got {typeof(T).Name}.");

        using var stream = new MemoryStream(data);
        var decoder = new BinaryDecoder(stream);
        var reader = new SpecificDefaultReader(schemaInstance.Schema, schemaInstance.Schema);
        return (T?)reader.Read(schemaInstance, decoder);
    }
}
