<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>FireflyFramework.Webhooks.Interfaces</RootNamespace>
    <PackageId>FireflyFramework.Webhooks.Interfaces</PackageId>
    <Description>Webhook public DTOs. Mirrors fireflyframework-webhooks-interfaces.</Description>
  </PropertyGroup>

</Project>
